### ISSUE TITLE
How not to copy Google Drive folder to local folder?

### ISSUE THREAD

**Issue by mvasin** [kbinani/gdsync#1]
First of all, thanks for the great piece of software!

When I sync `ruby gdsync.rb -rtu googledrive://some/remote_folder ~/some/local_folder`, can I avoid creating `remote_folder` inside `local_folder`?

I have tried `ruby gdsync.rb -rtu googledrive://remote_folder/ ~/local_folder` (no difference) and `ruby gdsync.rb -rtu googledrive://remote_folder/* ~/local_folder` (an error).

**Comment by kbinani** [comment]
@mvasin Thank you for reporting issue!
I've confirmed that this issue can be reproduced, and I'm preparing a fix for it.

`ruby gdsync.rb -rtu googledrive://remote_folder/ ~/local_folder` is correct command to copy directory contents without creating `remote_folder`, but gdsync ignores last `'/'` in source path.
